Q1:
		g++ Cannonballs.cpp -o Q1

Q2:
		g++ Power.cpp -o Q2

Q3:
		g++ GCD.cpp -o Q3

Q4:
		g++ DigitSum.cpp -o Q4

Q5:
		g++ Reverse.cpp -o Q5
Q6:
		g++ SelectionSort.cpp random.cpp -o Q6
Q7:
		g++ MergeSort.cpp random.cpp -o Q7

clean:
		find . -perm +100 -type f -delete
